using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Timing;
using Content.Shared._Maid.TradeShuttleConsole;

namespace Content.Client._Maid.TradeShuttleConsole;

[GenerateTypedNameReferences]
public sealed partial class TradeShuttleConsoleWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _gameTiming = default!;

    public event Action? OnActionButtonPressed;

    private StartEndTime? _ftlTime;

    public TradeShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ActionButton.OnPressed += _ => OnActionButtonPressed?.Invoke();
    }

    public void UpdateState(TradeShuttleConsoleUIState state)
    {
        var location = Loc.GetString($"trade-shuttle-console-location-{(state.OnTrade ? "trade" : "station")}");
        ControlledShuttle.Text = Loc.GetString(
            $"trade-shuttle-console-controlled-shuttle-{(state.ControlledShuttle is null ? "self" : "other")}",
            ("shuttleName", state.ControlledShuttle ?? "self")
        );

        switch (state)
        {
            case TradeShuttleConsoleFtlInProgressUIState ftl:
                StatusLabel.Text = Loc.GetString(
                    "trade-shuttle-console-status-ftl-progress",
                    ("ftlStatus", Loc.GetString($"shuttle-console-ftl-state-{ftl.FtlState}")),
                    ("destination", location)
                );
                ActionButton.Disabled = true;
                ActionButton.Text = Loc.GetString("trade-shuttle-console-button-ftl-progress");
                SetFtlTimer(ftl.FtlTime);
                break;
            case TradeShuttleConsoleIdleUIState idle:
                StatusLabel.Text = Loc.GetString(
                    "trade-shuttle-console-status-idle",
                    ("location", location)
                );
                ActionButton.Disabled = false;
                ActionButton.Text = Loc.GetString($"trade-shuttle-console-button-{(idle.OnTrade ? "call" : "recall")}");
                SetFtlTimer(null);
                break;
        }
    }

    private void SetFtlTimer(StartEndTime? ftl)
    {
        _ftlTime = ftl;
        if (ftl is null)
            return;

        TimerBar.Value = ftl.Value.ProgressAt(_gameTiming.CurTime);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_ftlTime is null)
            return;

        var progress = _ftlTime.Value.ProgressAt(_gameTiming.CurTime);
        TimerBar.Value = Math.Clamp(progress, 0f, 1f);
    }
}
