// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jesse Rougeau <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2023 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 12rabbits <53499656+12rabbits@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Alzore <140123969+Blackern5000@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Brandon Hu <103440971+Brandon-Huu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <65184747+Dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2024 Fildrance <fildrance@gmail.com>
// SPDX-FileCopyrightText: 2024 Firewatch <54725557+musicmanvr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <51352440+JIPDawg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <JIPDawg93@gmail.com>
// SPDX-FileCopyrightText: 2024 Mervill <mervills.email@gmail.com>
// SPDX-FileCopyrightText: 2024 Moomoobeef <62638182+Moomoobeef@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <koolthunder019@gmail.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers@gmail.com>
// SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
// SPDX-FileCopyrightText: 2024 PursuitInAshes <pursuitinashes@gmail.com>
// SPDX-FileCopyrightText: 2024 QueerNB <176353696+QueerNB@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Spessmann <156740760+Spessmann@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 dffdff2423 <dffdff2423@gmail.com>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2024 github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 pa.pecherskij <pa.pecherskij@interfax.ru>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 stellar-novas <stellar_novas@riseup.net>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._Maid.Lobby.UI; // Maid-Tweak
using Content.Client._RMC14.LinkAccount;
using Content.Client.Info;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!; // Maid-Tweak

        // Maid-Tweak-start
        public const string IconAHelp = "/Textures/Interface/VerbIcons/information.svg.192dpi.png";
        public const string IconHideUi = "/Textures/Interface/hamburger.svg.192dpi.png";
        public const string IconShowUi = "/Textures/Interface/VerbIcons/examine.svg.192dpi.png";

        public static readonly Color MenuIconNormal = Color.FromHex("#FFFFFF");
        public static readonly Color MenuIconHover = Color.FromHex("#F0C96A");
        public static readonly Color MenuIconDisabled = Color.FromHex("#555555");
        public static readonly Color ReadyGreen = Color.FromHex("#6ED18D");
        public static readonly Color ReadyRed = Color.FromHex("#DE4A44");
        public static readonly Color AHelpUnread = Color.FromHex("#E5534B");

        public bool UiHidden { get; private set; }

        private Label? _aHelpRest;
        private bool _aHelpUnread;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LayoutContainer.SetAnchorPreset(BottomSide, LayoutPreset.Wide);
            LayoutContainer.SetMarginTop(BottomSide, 8);
            LayoutContainer.SetMarginBottom(BottomSide, 8);

            LayoutContainer.SetAnchorPreset(VoteContainer, LayoutPreset.TopLeft);
            LayoutContainer.SetMarginLeft(VoteContainer, 20);
            LayoutContainer.SetMarginTop(VoteContainer, 56);

            LayoutContainer.SetAnchorPreset(HideUiButton, LayoutPreset.TopLeft);
            LayoutContainer.SetMarginLeft(HideUiButton, 14);
            LayoutContainer.SetMarginTop(HideUiButton, 10);

            LayoutContainer.SetAnchorPreset(ShowChangelogButton, LayoutPreset.BottomLeft);
            LayoutContainer.SetGrowVertical(ShowChangelogButton, LayoutContainer.GrowDirection.Begin);
            LayoutContainer.SetMarginLeft(ShowChangelogButton, 18);
            LayoutContainer.SetMarginTop(ShowChangelogButton, -48);
            LayoutContainer.SetMarginBottom(ShowChangelogButton, -48);

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            MenuDiscordButton.OnPressed += _ => UserInterfaceManager.GetUIController<LinkAccountUIController>().ToggleWindow();
            MenuCharacterSetupButton.OnPressed += _ => SwitchState(LobbyGuiState.CharacterSetup);
            MenuRulesButton.OnPressed += _ => new RulesAndInfoWindow().OpenCentered();

            HideUiButton.OnPressed += _ => SetUiHidden(!UiHidden);
            ToggleChangelogButton.OnPressed += _ => SetChangelogVisible(false);
            ShowChangelogButton.OnPressed += _ => SetChangelogVisible(true);

            BindMenuIcon(MenuCharacterSetupButton, CharacterIcon);
            BindMenuIcon(MenuRulesButton, RulesIcon);
            BindMenuIcon(OptionsButton, OptionsIcon);
            BindMenuIcon(MenuDiscordButton, DiscordIcon);
            BindMenuIcon(ObserveButton, ObserveIcon);
            BindMenuIcon(LeaveButton, LeaveIcon);

            AHelpIcon.ModulateSelfOverride = MenuIconNormal;
            ReadyIcon.IconColor = ReadyRed;
            ReadyIcon.Mode = ReadyStatusIcon.ReadyIconMode.NotReady;
            SetupAHelpCaption();

            // Maid-Tweak
            Chat.ChatWindowPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
            };

            foreach (var child in ChangelogScrollContainer.Children)
            {
                if (child is ScrollBar scrollBar)
                    scrollBar.AddStyleClass(StyleNano.StyleClassHiddenScrollbar);
            }
        }

        public void SetUiHidden(bool hidden)
        {
            UiHidden = hidden;
            BottomSide.Visible = !hidden;
            HideUiButton.TexturePath = hidden ? IconShowUi : IconHideUi;
            HideUiButton.ToolTip = Loc.GetString(hidden ? "ui-lobby-show-ui-button" : "ui-lobby-hide-ui-button");
        }

        public void SetChangelogVisible(bool visible)
        {
            ChangelogColumn.Visible = visible;
            ShowChangelogButton.Visible = !visible;
        }

        public void UpdateReadyVisuals(bool gameStarted, bool ready)
        {
            if (gameStarted)
            {
                ReadyIcon.Mode = ReadyStatusIcon.ReadyIconMode.Join;
                ReadyIcon.IconColor = MenuIconNormal;
                ReadyButton.Label.FontColorOverride = null;
                return;
            }

            ReadyIcon.Mode = ready
                ? ReadyStatusIcon.ReadyIconMode.Ready
                : ReadyStatusIcon.ReadyIconMode.NotReady;
            var color = ready ? ReadyGreen : ReadyRed;
            ReadyIcon.IconColor = color;
            ReadyButton.Label.FontColorOverride = color;
        }

        public void UpdateAHelpVisuals(bool unread, bool open)
        {
            _aHelpUnread = unread;
            SetIcon(AHelpIcon, IconAHelp);
            RefreshAHelpCaption(false);
            if (unread)
            {
                AHelpIcon.ModulateSelfOverride = AHelpUnread;
                return;
            }

            AHelpIcon.ModulateSelfOverride = open
                ? Color.White
                : Color.FromHex("#6A6A6A");
        }

        private void SetupAHelpCaption()
        {
            AHelpButton.Label.Visible = false;
            var text = Loc.GetString("ui-lobby-ahelp-button");
            var letter = text.Length > 0 ? text[..1] : "A";
            var rest = text.Length > 1 ? text[1..] : "Help";

            _aHelpRest = new Label
            {
                Text = rest,
                StyleClasses = { StyleNano.StyleClassLobbyMenuText },
                FontColorOverride = MenuIconNormal,
                VerticalAlignment = VAlignment.Center,
            };

            AHelpButton.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 0,
                MouseFilter = MouseFilterMode.Ignore,
                Children =
                {
                    new Label
                    {
                        Text = letter,
                        StyleClasses = { StyleNano.StyleClassLobbyMenuText },
                        FontColorOverride = AHelpUnread,
                        VerticalAlignment = VAlignment.Center,
                    },
                    _aHelpRest,
                },
            });

            AHelpButton.OnMouseEntered += _ => RefreshAHelpCaption(true);
            AHelpButton.OnMouseExited += _ => RefreshAHelpCaption(false);
        }

        private void RefreshAHelpCaption(bool hover)
        {
            if (_aHelpRest == null)
                return;

            _aHelpRest.FontColorOverride = _aHelpUnread
                ? AHelpUnread
                : hover ? MenuIconHover : MenuIconNormal;
        }

        public void UpdateObserveIcon(bool enabled)
        {
            ObserveIcon.ModulateSelfOverride = enabled ? MenuIconNormal : MenuIconDisabled;
            if (ObserveButton.Label != null)
                ObserveButton.Label.FontColorOverride = enabled ? null : MenuIconDisabled;
        }

        public void UpdateDiscordLinked(bool linked)
        {
            MenuDiscordButton.Disabled = linked;
            DiscordIcon.ModulateSelfOverride = linked ? MenuIconDisabled : MenuIconNormal;
            if (MenuDiscordButton.Label != null)
                MenuDiscordButton.Label.FontColorOverride = linked ? MenuIconDisabled : null;
            MenuDiscordButton.ToolTip = linked
                ? Loc.GetString("ui-lobby-discord-already-linked")
                : null;
        }

        private void BindMenuIcon(Button button, TextureRect icon)
        {
            icon.ModulateSelfOverride = MenuIconNormal;
            button.OnMouseEntered += _ =>
            {
                if (!button.Disabled)
                    icon.ModulateSelfOverride = MenuIconHover;
            };
            button.OnMouseExited += _ =>
            {
                icon.ModulateSelfOverride = button.Disabled ? MenuIconDisabled : MenuIconNormal;
            };
        }

        private void SetIcon(TextureRect icon, string path)
        {
            icon.Texture = _resourceCache.GetTexture(path);
        }
        // Maid-Tweak-end

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    BottomSide.Visible = !UiHidden; // Maid-Tweak
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) MainContainer.PixelWidth; // Maid-Tweak

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        BottomSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            Default,
            CharacterSetup
        }
    }
}
