// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 c4llv07e <38111072+c4llv07e@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.Access;
using Content.Shared.Roles;

namespace Content.Client.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class AccessLevelControl : GridContainer
{
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;

    public readonly Dictionary<ProtoId<AccessLevelPrototype>, Button> ButtonsList = new();

    public AccessLevelControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("accesslevelcontrol");
    }

    public void Populate(List<ProtoId<AccessLevelPrototype>> accessLevels, IPrototypeManager prototypeManager)
    {
        foreach (var access in accessLevels)
        {
            if (!prototypeManager.TryIndex(access, out var accessLevel))
            {
                _sawmill.Error($"Unable to find accesslevel for {access}");
                continue;
            }

            var newButton = new Button
            {
                Text = accessLevel.GetAccessLevelName(),
                ToggleMode = true,
            };
            AddChild(newButton);
            ButtonsList.Add(accessLevel.ID, newButton);
        }
    }

    //Maid edit start
    public void PopulateWithDepartmentColors(
        List<ProtoId<AccessLevelPrototype>> accessLevels,
        IPrototypeManager prototypeManager)
    {
        var styles = BuildAccessStyleMap(prototypeManager);

        foreach (var access in accessLevels)
        {
            if (!prototypeManager.TryIndex(access, out var accessLevel))
            {
                _sawmill.Error($"Unable to find accesslevel for {access}");
                continue;
            }

            var newButton = new Button
            {
                Text = accessLevel.GetAccessLevelName(),
                ToggleMode = true,
            };

            if (styles.TryGetValue(accessLevel.ID, out var styleClass))
                newButton.AddStyleClass(styleClass);

            AddChild(newButton);
            ButtonsList.Add(accessLevel.ID, newButton);
        }
    }

    private static Dictionary<ProtoId<AccessLevelPrototype>, string> BuildAccessStyleMap(IPrototypeManager prototypeManager)
    {
        var styles = new Dictionary<ProtoId<AccessLevelPrototype>, string>();

        var departments = prototypeManager.EnumeratePrototypes<DepartmentPrototype>().ToList();
        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            foreach (var jobId in department.Roles)
            {
                if (!prototypeManager.TryIndex(jobId, out var job))
                    continue;

                foreach (var access in job.Access)
                {
                    styles.TryAdd(access, department.ButtonStyle);
                }

                foreach (var groupId in job.AccessGroups)
                {
                    if (!prototypeManager.TryIndex(groupId, out var group))
                        continue;

                    foreach (var access in group.Tags)
                    {
                        styles.TryAdd(access, department.ButtonStyle);
                    }
                }
            }
        }

        return styles;
    }
    //Maid edit end

    public void UpdateState(
        List<ProtoId<AccessLevelPrototype>> pressedList,
        List<ProtoId<AccessLevelPrototype>>? enabledList = null)
    {
        foreach (var (accessName, button) in ButtonsList)
        {
            button.Pressed = pressedList.Contains(accessName);
            button.Disabled = !(enabledList?.Contains(accessName) ?? true);
        }
    }
}