// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Illiux <newoutlook@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Júlio César Ueti <52474532+Mirino97@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2024 Crotalus <Crotalus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
// Maid edit start
using System.Linq;
using System.Numerics;
using Content.Shared.Ghost;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private const int ColumnCount = 5;
        private const string AntagonistStyleClass = "ButtonColorAntagonistDepartment";
        private const string PlaceStyleClass = "ButtonColorSpecificDepartment";

        private List<GhostWarpPlayer> _playerWarps = new();
        private List<GhostWarpPlace> _placeWarps = new();
        private List<GhostWarpGlobalAntagonist> _antagonistWarps = new();

        private readonly List<GhostWarpPlayer> _alivePlayers = new();
        private readonly List<GhostWarpPlayer> _deadPlayers = new();
        private readonly List<GhostWarpPlayer> _ghostPlayers = new();
        private readonly List<GhostWarpPlayer> _leftPlayers = new();

        private string _searchText = string.Empty;

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            SearchBar.OnTextChanged += OnSearchTextChanged;
            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void UpdateWarps(
            List<GhostWarpPlayer> players,
            List<GhostWarpPlace> places,
            List<GhostWarpGlobalAntagonist> antagonists)
        {
            _playerWarps = players;
            _placeWarps = places;
            _antagonistWarps = antagonists;
        }

        public void Populate()
        {
            GhostTeleportContainer.DisposeAllChildren();

            _playerWarps = _playerWarps.OrderBy(w => w.Name).ToList();
            _placeWarps = _placeWarps.OrderBy(w => w.Name).ToList();
            _antagonistWarps = _antagonistWarps.OrderBy(w => w.Name).ToList();

            AllocatePlayers();

            AddAntagonistButtons(_antagonistWarps);
            AddPlayerButtons(_alivePlayers, "ghost-teleport-menu-alive-label");
            AddPlayerButtons(_deadPlayers, "ghost-teleport-menu-dead-label");
            AddPlayerButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label");
            AddPlayerButtons(_leftPlayers, "ghost-teleport-menu-left-label");
            AddPlaceButtons(_placeWarps);
        }

        private void AllocatePlayers()
        {
            _alivePlayers.Clear();
            _deadPlayers.Clear();
            _ghostPlayers.Clear();
            _leftPlayers.Clear();

            foreach (var warp in _playerWarps)
            {
                if (warp.IsDead)
                    _deadPlayers.Add(warp);
                else if (warp.IsLeft)
                    _leftPlayers.Add(warp);
                else if (warp.IsAlive)
                    _alivePlayers.Add(warp);
                else if (warp.IsGhost)
                    _ghostPlayers.Add(warp);
            }
        }

        private void AddPlayerButtons(List<GhostWarpPlayer> players, string sectionLoc)
        {
            var matching = players.Where(p => Matches(p.Name)).ToList();

            if (matching.Count == 0)
                return;

            var section = CreateSection(sectionLoc);

            foreach (var group in GroupByDepartment(matching))
            {
                var department = GetDepartment(group[0].DepartmentId);

                var departmentName = department != null
                    ? Loc.GetString(department.Name)
                    : Loc.GetString("ghost-teleport-menu-unknown-department");

                var label = new Label
                {
                    Text = $"{departmentName}: {group.Count}",
                    StyleClasses = { "LabelSecondaryColor" },
                };

                var grid = new GridContainer { Columns = ColumnCount };

                foreach (var player in group)
                {
                    grid.AddChild(CreateWarpButton(
                        player.Name,
                        player.JobName,
                        department?.ButtonStyle ?? PlaceStyleClass,
                        player.Entity));
                }

                section.AddChild(label);
                section.AddChild(grid);
            }

            GhostTeleportContainer.AddChild(section);
        }

        private void AddAntagonistButtons(List<GhostWarpGlobalAntagonist> antagonists)
        {
            var matching = antagonists.Where(a => Matches(a.Name)).ToList();

            if (matching.Count == 0)
                return;

            var section = CreateSection("ghost-teleport-menu-antagonists-label");

            foreach (var group in GroupByAntagonist(matching))
            {
                var label = new Label
                {
                    Text = $"{group[0].GroupName}: {group.Count}",
                    StyleClasses = { "LabelSecondaryColor" },
                };

                var grid = new GridContainer { Columns = ColumnCount };

                foreach (var antagonist in group)
                {
                    grid.AddChild(CreateWarpButton(
                        antagonist.Name,
                        antagonist.GroupDescription,
                        AntagonistStyleClass,
                        antagonist.Entity));
                }

                section.AddChild(label);
                section.AddChild(grid);
            }

            GhostTeleportContainer.AddChild(section);
        }

        private void AddPlaceButtons(List<GhostWarpPlace> places)
        {
            var matching = places.Where(p => Matches(p.Name)).ToList();

            if (matching.Count == 0)
                return;

            var section = CreateSection("ghost-teleport-menu-locations-label");

            var label = new Label
            {
                Text = $"{Loc.GetString("ghost-teleport-menu-count-label")}: {matching.Count}",
                StyleClasses = { "LabelSecondaryColor" },
            };

            var grid = new GridContainer { Columns = ColumnCount };

            foreach (var place in matching)
            {
                grid.AddChild(CreateWarpButton(place.Name, place.Description, PlaceStyleClass, place.Entity));
            }

            section.AddChild(label);
            section.AddChild(grid);

            GhostTeleportContainer.AddChild(section);
        }

        private Button CreateWarpButton(string text, string tooltip, string styleClass, NetEntity target)
        {
            var button = new Button
            {
                Text = text,
                TextAlign = Label.AlignMode.Center,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                StyleClasses = { styleClass },
                ToolTip = tooltip,
                TooltipDelay = 0.1f,
                SetWidth = 180,
                ClipText = true,
            };

            button.OnPressed += _ => WarpClicked?.Invoke(target);

            return button;
        }

        private static BoxContainer CreateSection(string sectionLoc)
        {
            var section = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };

            section.AddChild(new Label
            {
                Text = Loc.GetString(sectionLoc),
                StyleClasses = { "LabelBig" },
            });

            return section;
        }

        private DepartmentPrototype? GetDepartment(string departmentId)
        {
            return _prototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var department)
                ? department
                : null;
        }

        private List<List<GhostWarpPlayer>> GroupByDepartment(List<GhostWarpPlayer> players)
        {
            return players
                .GroupBy(p => p.DepartmentId)
                .OrderByDescending(g => GetDepartment(g.Key)?.Weight ?? int.MinValue)
                .ThenBy(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private static List<List<GhostWarpGlobalAntagonist>> GroupByAntagonist(List<GhostWarpGlobalAntagonist> antagonists)
        {
            return antagonists
                .GroupBy(a => a.GroupName)
                .OrderBy(g => g.First().GroupWeight)
                .ThenBy(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private bool Matches(string name)
        {
            return string.IsNullOrEmpty(_searchText)
                   || name.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            Populate();
            // Reset scroll bar so they can see the relevant results.
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
// Maid edit end